name: nixless
description: What if you just derove?
inputs:
  registry:
    description: Registry URL
    required: true
  image:
    description: Image name (includes registry)
    required: true
  tag:
    description: Image tag
    required: true
runs:
  using: "composite"
  steps:
  - run: curl https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin
    shell: bash
  - run: |
      sudo apt-get -y update
      sudo apt-get -y install skopeo
    shell: bash
  - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    shell: bash
  - run: just publish ${{ inputs.registry}} ${{ inputs.image }} ${{ inputs.tag }}
    shell: bash
